# Generated by Django 4.0.4 on 2022-11-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='images/')),
                ('username', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('username', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='images/')),
                ('phonenumber', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=100)),
                ('bio', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
