# Generated by Django 4.0.4 on 2022-11-19 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_registration_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths_marks', models.CharField(default='', max_length=100)),
                ('physics_marks', models.CharField(default='', max_length=100)),
                ('chemistry_marks', models.CharField(default='', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_registration')),
            ],
        ),
    ]
