# Generated by Django 4.0.4 on 2022-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_registration',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
