# Generated by Django 4.0.4 on 2022-11-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_registration_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
